name: Publish site

on:
  push:
    branches:
      - pelican

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install theme
      run: |
        pelican-themes -i pelican-themes/bs5
    - name: Build site
      run: |
        pelican content -o output -s pelicanconf.py
    - name: Update local site branch
      run: |
        ghp-import output -b master
    - name: Push local site to remote
      run: |
        git push -f origin master
